// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgParJ3DNL_KqKqgCRJy3Fa7fnntmvf_o',
    appId: '1:61742263920:web:88856f0048ce3324934eb5',
    messagingSenderId: '61742263920',
    projectId: 'showyou-41c9b',
    authDomain: 'showyou-41c9b.firebaseapp.com',
    storageBucket: 'showyou-41c9b.appspot.com',
    measurementId: 'G-ME469ZD54Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4QaJvoty0G-iFuM--4ua60dtY_4iHLBo',
    appId: '1:61742263920:android:fc9faaa63e1a3744934eb5',
    messagingSenderId: '61742263920',
    projectId: 'showyou-41c9b',
    storageBucket: 'showyou-41c9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpUBLt-kccy_MmLg3jk_3178so96hFeY',
    appId: '1:61742263920:ios:42ca463fd68fbb49934eb5',
    messagingSenderId: '61742263920',
    projectId: 'showyou-41c9b',
    storageBucket: 'showyou-41c9b.appspot.com',
    iosBundleId: 'com.example.showYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmpUBLt-kccy_MmLg3jk_3178so96hFeY',
    appId: '1:61742263920:ios:07cedde3feb2de0c934eb5',
    messagingSenderId: '61742263920',
    projectId: 'showyou-41c9b',
    storageBucket: 'showyou-41c9b.appspot.com',
    iosBundleId: 'com.example.showYou.RunnerTests',
  );
}
